version: "3"
services:
  netology-db:
    image: postgres:latest
    container_name: tretyakov.va-netology-db
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: tretyakovva12!3!! 
      POSTGRES_DB: tretyakovva_db
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      tretyakovva-my-netology-hw:
        ipv4_address: 172.22.0.2
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    links:
      - netology-db
    container_name: tretyakovva-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: tretyakovva@ilove-netology.com
      PGADMIN_DEFAULT_PASSWORD: tretyakovva
    ports:
      - 61231:80
    networks:
      tretyakovva-my-netology-hw:
        ipv4_address: 172.22.0.3
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    links:
      - netology-db
    container_name: tretyakovva-netology-zabbix-frontend
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tretyakovva12!3!!
    ports:
      - 10051:10051
    networks:
      tretyakovva-my-netology-hw:
        ipv4_address: 172.22.0.4
    restart: always

  zabbix_wgui:
    image: zabbix/zabbix-web-apache-pgsql
    links:
    - netology-db
    container_name: netology_zabbix_wgui
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: tretyakovva12!3!!
      ZBX_SERVER_HOST: "zabbix_wgui"
      PHP_TZ: "Europe/Moscow"
    ports:
    - 80:8080
    - 443:8443
    networks:
      tretyakovva-my-netology-hw:
        ipv4_address: 172.22.0.5
    restart: always

networks:
  tretyakovva-my-netology-hw:
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/24

